### PR TITLE
max skew time + batch submission time calculation refactor

### LINKED ISSUE #1282: skew time is using genesis creation time when there is no state update submitted.
this leads to an incorrect skew time when no state update is still submitted. it should use first block creation time when there is no state update.

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

This PR solves two issues:

 - submission time when no state update is submitted should take first block as a reference, and no the genesis time (to calculate skew time).
 - batch_submission_time (config) should be based on submissions time, and no based on block times, otherwise it maybe that the submissions are not exactly every batch_submission_time when no block production. 

Close #1282 ,#1287

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/submit.go [hunk 1]
```diff
@@ -314,11 +311,36 @@ func (m *Manager) UpdateLastSubmittedHeight(event pubsub.Message) {
 	}
 }
 
+func (m *Manager) GetLastBlockInSettlementTime() (time.Time, error) {
+	lastBlockInSettlement, err := m.Store.LoadBlock(m.LastSettlementHeight.Load())
```
Comment (omritoptix) [inline block/submit.go:315]: I think the LastSettlementHeight may get pruned no?

```go
pruningHeight = min(m.NextHeightToSubmit(), uint64(retainHeight))
```

if that's the case and we fallback to first block it may cause unnecessary halt.

Comment (srene) [reply block/submit.go:315]: true. good catch. i keep last submitted block without pruning to enable skew time calculation and keep code simplicity.

**Comment by danwt** [comment]
https://github.com/dymensionxyz/dymint/issues/1282

**Review by omritoptix — DISMISSED** [review]

**Review by omritoptix — APPROVED** [review]
