### PR TITLE
fix(da): check DA client type before trying to fetch batch

### LINKED ISSUE #651: full-node should check valid da path before trying to get blob
it should be avoided trying to get blob using da path that does not match the da config in the node (e.g. da path is for another da)  and log error according to that

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Close #651 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/retriever.go [hunk 1]
```diff
@@ -79,6 +79,7 @@ func (m *Manager) processNextDABatch(daMetaData *da.DASubmitMetaData) error {
 	m.logger.Debug("trying to retrieve batch from DA", "daHeight", daMetaData.Height)
 	batchResp := m.fetchBatch(daMetaData)
 	if batchResp.Code != da.StatusSuccess {
+		m.logger.Error("Failed fetching batch from DA", batchResp.Message)
```
Comment (omritoptix) [inline block/retriever.go:82]: @danwt wouldn't like that u use the "Failed' word in an error logger :) Better remove.

File: block/retriever.go [hunk 2]
```diff
@@ -108,6 +109,17 @@ func (m *Manager) processNextDABatch(daMetaData *da.DASubmitMetaData) error {
 }
 
 func (m *Manager) fetchBatch(daMetaData *da.DASubmitMetaData) da.ResultRetrieveBatch {
+
```
Comment (omritoptix) [inline block/retriever.go:112]: I'd suggest remove the blank line

Comment (srene) [reply block/retriever.go]: removed

File: block/retriever.go (hunk 1 above)
Comment (srene) [reply block/retriever.go]: msg udpated

**Review by omritoptix — DISMISSED** [review]

File: block/retriever.go [hunk 3]
```diff
@@ -108,6 +109,16 @@ func (m *Manager) processNextDABatch(daMetaData *da.DASubmitMetaData) error {
 }
 
 func (m *Manager) fetchBatch(daMetaData *da.DASubmitMetaData) da.ResultRetrieveBatch {
+	// Check DA client
+	if daMetaData.Client != m.dalc.GetClientType() {
```
Comment (mtsitrin) [inline block/retriever.go:113]: is this the only thing need to be validated on the SL batch? what about namespace?

**Review by mtsitrin — DISMISSED** [review]

File: block/retriever.go (hunk 3 above)
Comment (omritoptix) [reply block/retriever.go:113]: yea good thinking.

Comment (srene) [reply block/retriever.go]: i added a namespace check for celestia, which i think is the only da using namespace id. 
However, i think namespace id configuration needs to be refactored, since there are multiple params in the config for that, and actually it could be directly derived from chain_id without having to pass it to the full-node or having a config param for that

File: da/celestia/celestia.go [hunk 4]
```diff
@@ -399,6 +400,17 @@ func (c *DataAvailabilityLayerClient) retrieveBatchesNoCommitment(dataLayerHeigh
 
 func (c *DataAvailabilityLayerClient) CheckBatchAvailability(daMetaData *da.DASubmitMetaData) da.ResultCheckBatch {
 	var availabilityResult da.ResultCheckBatch
+	//check namespace
+	if !slices.Equal(daMetaData.Namespace, c.config.NamespaceID.Bytes()) {
```
Comment (omritoptix) [inline da/celestia/celestia.go:404]: why isn't this check one on the `fetchBatch`? also may be worth to simply write a `validateBasic` method on the daMetaData after fetching and test it all matches the current configuration

File: block/errors.go [hunk 5]
```diff
@@ -5,4 +5,5 @@ import "errors"
 var (
 	ErrNonRecoverable = errors.New("non recoverable")
 	ErrRecoverable    = errors.New("recoverable")
+	ErrWrongDA        = errors.New("wrong DA")
```
Comment (danwt) [inline block/errors.go:8]: can we specify a bit more: wrong in what sense?

Comment (danwt) [reply block/errors.go:8]: I guess it's included in the context so it's fine

File: da/errors.go [hunk 6]
```diff
@@ -4,19 +4,21 @@ import "errors"
 
 var (
 	// ErrFailedTxBuild is returned when transaction build fails.
-	ErrTxBroadcastConfigError = errors.New("Failed building tx")
+	ErrTxBroadcastConfigError = errors.New("failed building tx")
 	// ErrFailedTxBroadcast is returned when transaction broadcast fails.
-	ErrTxBroadcastNetworkError = errors.New("Failed broadcasting tx")
+	ErrTxBroadcastNetworkError = errors.New("failed broadcasting tx")
 	// ErrTxBroadcastTimeout is returned when transaction broadcast times out.
```
Comment (danwt) [inline da/errors.go:10]: dont need failed..

**Review by omritoptix — APPROVED** [review]

**Review by danwt — CHANGES_REQUESTED** [review]
How about having a manager method to verify the settlement batch instead?

https://github.com/dymensionxyz/dymint/blob/8f0d22e5c61f40190df043b36888e3684d4bfb0e/block/retriever.go#L47-L51
