### PR TITLE
fix(rpc): panic and publish health event only on create batch error

### LINKED ISSUE #902: health endpoint isn't updated if batch fails creation
if e.g failing to create a batch:

`ERRO[43500] handle submission trigger[error create next batch: batch end height must be greater than start height. EndHeight 26643, StartHeight 26644]
`
no health event is emitted and node operator has no visiblity about the node failing to send the batch

### PR DESCRIPTION
**Pull request by zale144**
# PR Standards

## Opening a pull request should be able to meet the following requirements

--

PR naming convention: https://hackmd.io/@nZpxHZ0CT7O5ngTp0TP9mg/HJP_jrm7A

---

Close #902 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

## Summary by CodeRabbit

- **New Features**
  - Improved application stability by ensuring blocked processes are properly terminated during shutdown.
  - Enhanced error handling with error logging for better diagnosis and troubleshooting.

- **Performance Improvements**
  - Added health status monitoring for improved system health tracking.

### CODE REVIEW

File: block/submit.go [hunk 1]
```diff
@@ -24,8 +24,23 @@
 	maxSizeC := make(chan struct{}, m.Conf.MaxSupportedBatchSkew)
 	go m.AccumulatedDataLoop(ctx, maxSizeC)
 
+	handleSubmitLoopPanic := func() {
+		// recover from panic, emit health status event and return the error
+		var err error
+		if r := recover(); r != nil {
```
[the remark this answers is not in the document]
Comment (danwt) [reply block/submit.go:30]: @zale144

[the remark this answers is not in the document]
Comment (danwt) [reply block/submit.go:30]: doesnt work AFAIU

**Review by danwt — CHANGES_REQUESTED** [review]

File: block/submit.go [hunk 2]
```diff
@@ -26,6 +27,17 @@ func (m *Manager) SubmitLoop(ctx context.Context) {
 
 	// defer func to clear the channels to release blocked goroutines on shutdown
 	defer func() {
+		// recover from panic, emit health status event and return the error
```
Comment (mtsitrin) [inline block/submit.go:30]: why u handle it in recover. instead of just avoiding the panic here
```
err := m.HandleSubmissionTrigger()
		if err != nil {
			panic(fmt.Errorf("handle submission trigger: %w", err))
		}
```

File: block/submit.go [hunk 3]
```diff
@@ -26,6 +27,17 @@ func (m *Manager) SubmitLoop(ctx context.Context) {
...
+		var err error
+		if r := recover(); r != nil {
+			m.logger.Error(fmt.Errorf("handle submission trigger: %v", r).Error())
+			err, _ = r.(error)
+		}
+		// new context because previous one is canceled
```
Comment (mtsitrin) [inline block/submit.go:36]: the defer will return, it won't run the loop again

**Review by mtsitrin — CHANGES_REQUESTED** [review]

File: block/submit.go (hunk 2 above)
Comment (zale144) [reply block/submit.go:30]: I guess the idea is that it would be considered an unrecoverable error, so might as well panic. However, we would still like to get an event about it

File: block/submit.go (hunk 3 above)
Comment (zale144) [reply block/submit.go:36]: yes

File: block/submit.go (hunk 2 above)
Comment (mtsitrin) [reply block/submit.go:30]: @zale144 why we need the event if the rpc server gonna be shut down anyway due to the panic?
don't we need `no panic + event` instead of the existing panic?

**Review by mtsitrin — COMMENTED** [review]
as discussed, we need to stop production in this case.
maybe the entire blockManager's context can be closed

**Review by mtsitrin — APPROVED** [review]

File: block/manager.go [hunk 4]
```diff
@@ -41,6 +43,9 @@ type Manager struct {
 	State    *types.State
 	Executor *Executor
 
+	// Context
+	cancelCtx context.CancelFunc
```
Comment (danwt) [inline block/manager.go:47]: This is a complete abuse / anti-pattern of how to write go code and how to use contexts

https://stackoverflow.com/questions/70042646/best-practices-on-go-context-cancelation-functions

You need to do something like instead https://stackoverflow.com/a/70042766

Sorry but this is just wrong golang

**Review by danwt — CHANGES_REQUESTED** [review]

File: block/manager.go (hunk 4 above)
Comment (zale144) [reply block/manager.go:47]: Sure there are more idiomatic ways to do this, but I think calling it "complete abuse" of how to write go code is a bit out of line. 
 
Given the time constraints, I don't think these are the most critical issues to deal with right now.

**Review by mtsitrin — APPROVED** [review]
