### PR TITLE
fix(block manage): reducing batch overhead size when reaping Txs from mempool

### LINKED ISSUE #885: Commit size + Block size could be greater than batch size
The issue here is that though we take for the block size the minimum between the batch size and the block size consensus params, in [those lines](https://github.com/dymensionxyz/dymint/blob/main/block/submit.go#L164-L172) we also append the commit to the batch (+ the overhead of the struct of the batch itself) so in some cases the batch won't get populated with any blocks (as it may be that the first block in the batch + commit > max batch size) which would lead to inability to submit batches.

### PR DESCRIPTION
**Pull request by mtsitrin**
# PR Standards

## Opening a pull request should be able to meet the following requirements

--

PR naming convention: https://hackmd.io/@nZpxHZ0CT7O5ngTp0TP9mg/HJP_jrm7A

---

Close #885 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/types.go [hunk 1]
```diff
@@ -8,6 +8,11 @@ import (
 )
 
 // TODO: move to types package
+
+const (
+	BatchOverhead = 700 // 500 block overhead + 117 for commit + 10 for batch overhead + safety margin
```
Comment (omritoptix) [inline block/types.go:13]: not sure I understand how it was calculated.
also Is this in bytes? can we make it configurable? 
also maybe it can be a percentage/factor of the block size? vs hardcoded bytes?

Comment (mtsitrin) [reply block/types.go]: refactored it

File: block/submit_test.go [hunk 2]
```diff
@@ -12,17 +12,112 @@ import (
...
+		var blocksize, commitSize int
+		for _, block := range batch.Blocks {
+			blocksize += block.ToProto().Size()
+		}
+		for _, commit := range batch.Commits {
+			commitSize += commit.ToProto().Size()
+		}
+
+		// we assert that the batch size is not larger than the maxBatchSize
+		assert.LessOrEqual(t, batchSize, int(maxBatchSize), tcase.name)
```
Comment (danwt) [inline block/submit_test.go:111]: can you move this up a few lines so that the logging-only computation is clearly demarcated from the actual thing being tested

File: block/submit_test.go [hunk 3]
```diff
@@ -221,3 +316,79 @@ func TestSubmissionByBatchSize(t *testing.T) {
 		}
 	}
 }
+
+func TestFullyPopulatedBlock(t *testing.T) {
```
Comment (danwt) [inline block/submit_test.go:320]: needs description of what it tests

**Review by danwt — CHANGES_REQUESTED** [review]
Looks like it works

I left some readability requests

BTW

Maybe instead of using a threshold like 90%

We can just binary search until we get something that makes maximum use of the space without overfilling. (Using a good start point to note be wasteful)

**Review by danwt — APPROVED** [review]
Nice work

**Review by omritoptix — APPROVED** [review]
