### PR TITLE
fix(manager/indexer): pruning fixes 

### LINKED ISSUE #1145: Possible memory leak while pruning

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

## Opening a pull request should be able to meet the following requirements

--

PR naming convention: https://hackmd.io/@nZpxHZ0CT7O5ngTp0TP9mg/HJP_jrm7A

---

Close #1145 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: indexers/txindex/kv/kv.go [hunk 1]
```diff
@@ -570,15 +571,16 @@ LOOP:
...
 	if err != nil {
 		return 0, err
 	}
 	return pruned, nil
 }
 
-func (txi *TxIndex) pruneTxs(from, to uint64) (uint64, error) {
+func (txi *TxIndex) pruneTxsAndEvents(from, to uint64) (uint64, error) {
 	pruned := uint64(0)
+	tobeFlushed := uint64(0)
```
Comment (omritoptix) [inline indexers/txindex/kv/kv.go:583]: tobe?

File: indexers/txindex/kv/kv.go [hunk 2]
```diff
@@ -592,30 +594,41 @@ func (txi *TxIndex) pruneTxs(from, to uint64) (uint64, error) {
 
 	for h := from; h < to; h++ {
 
+		// first all events are pruned associated to the same height
+		prunedEvents, err := txi.pruneEvents(h, batch)
+		if err != nil {
+			continue
```
Comment (omritoptix) [inline indexers/txindex/kv/kv.go:600]: should we log here at least something so will know we had problem pruning?

**Review by omritoptix — CHANGES_REQUESTED** [review]
Still in the middle of the review

**Comment by danwt** [comment]
build n test failing sir

File: indexers/txindex/kv/kv.go (hunk 1 above)
Comment (srene) [reply indexers/txindex/kv/kv.go]: renamed

File: indexers/txindex/kv/kv.go (hunk 2 above)
Comment (srene) [reply indexers/txindex/kv/kv.go:601]: added

File: block/pruning.go [hunk 3]
```diff
@@ -2,44 +2,46 @@ package block
 
 import (
 	"context"
-	"fmt"
 )
 
-// PruneBlocks prune all block related data from dymint store up to (but not including) retainHeight. It returns the number of blocks pruned, used for testing.
-func (m *Manager) PruneBlocks(retainHeight uint64) (uint64, error) {
+// PruneBlocks prune all block related data from dymint store up to (but not including) retainHeight.
+func (m *Manager) PruneBlocks(retainHeight uint64) {
```
[the remark this answers is not in the document]
Comment (srene) [reply block/pruning.go:8]: added inline func for logging

File: block/pruning.go [hunk 4]
```diff
@@ -2,44 +2,46 @@ package block
...
-		return 0, fmt.Errorf("prune block store: %w", err)
+		m.logger.Error("pruning block store", "retain_height", retainHeight, "err", err)
+	} else {
+		m.logger.Debug("dymint store pruned", "from", m.State.BaseHeight, "to", retainHeight, "pruned", pruned)
+		m.State.BaseHeight = retainHeight
 	}
 
-	m.State.BaseHeight = retainHeight
+	// store state with base heights updates
 	_, err = m.Store.SaveState(m.State, nil)
```
[the remark this answers is not in the document]
Comment (srene) [reply block/pruning.go]: baseheight moved to store outside state

File: block/manager.go [hunk 5]
```diff
@@ -101,6 +101,9 @@ type Manager struct {
 
 	// validates all non-finalized state updates from settlement, checking there is consistency between DA and P2P blocks, and the information in the state update.
 	SettlementValidator *SettlementValidator
+
+	// BaseHeight is the height of the first block we have in store after pruning.
+	BaseHeight uint64
```
Comment (omritoptix) [inline block/manager.go:106]: redundant?

File: store/pruning.go [hunk 6]
```diff
@@ -1,24 +1,23 @@
...
+	prunedBlocks := uint64(0)
+	from, err := s.LoadBaseHeight()
+	if errors.Is(err, gerrc.ErrNotFound) {
+		logger.Error("load store base height", "err", err)
+	} else if err != nil {
+		return prunedBlocks, err
 	}
-
-	prunedBlocks, err := s.pruneBlocks(from, to, logger)
+	prunedBlocks, err = s.pruneBlocks(from, to, logger)
```
Comment (omritoptix) [inline store/pruning.go:20]: if we e.g get erorr here, than we still save the `to` as base height. (i.e some stores succeeded and some not).
not sure if critical for now but probably worth opening an issue on it otherwise you have stores which are partially pruned.

File: rpc/client/client.go [hunk 7]
```diff
@@ -325,8 +325,12 @@ func (c *Client) GenesisChunked(context context.Context, id uint) (*ctypes.Resul
 func (c *Client) BlockchainInfo(ctx context.Context, minHeight, maxHeight int64) (*ctypes.ResultBlockchainInfo, error) {
 	const limit int64 = 20
 
-	minHeight, maxHeight, err := filterMinMax(
-		int64(c.node.BlockManager.State.BaseHeight),
+	baseHeight, err := c.node.BlockManager.Store.LoadBaseHeight()
```
Comment (omritoptix) [inline rpc/client/client.go:328]: currently we only set base height when pruning. it means if we never set pruning, will never have base height and we won't be able to serve this method.

when was base height saved before?

File: indexers/txindex/indexer_service.go [hunk 8]
```diff
@@ -99,14 +102,33 @@ func (is *IndexerService) OnStop() {
 }
 
 // Prune removes tx and blocks indexed up to (but not including) a height.
-func (is *IndexerService) Prune(from, to uint64) error {
-	_, err := is.blockIdxr.Prune(from, to, is.Logger)
+func (is *IndexerService) Prune(to uint64, s store.Store) (uint64, error) {
+	// load indexer base height
+	indexerBaseHeight, err := s.LoadIndexerBaseHeight()
```
Comment (omritoptix) [inline indexers/txindex/indexer_service.go:107]: seems that if we fail to loa the height we just log it and the `indexerBaseHeight` will be set to 0.
this means tha the pruning functions will be called with `from` 0 (e.g blockIndexer) (and may unncessarily iterate tons of indexes.)

File: p2p/client.go [hunk 9]
```diff
@@ -221,13 +229,14 @@ func (c *Client) SaveBlock(ctx context.Context, height uint64, blockBytes []byte
...
-func (c *Client) RemoveBlocks(ctx context.Context, from, to uint64) error {
-	if from <= 0 {
-		return fmt.Errorf("from height must be greater than 0: %w", gerrc.ErrInvalidArgument)
-	}
+func (c *Client) RemoveBlocks(ctx context.Context, to uint64) (uint64, error) {
+	prunedBlocks := uint64(0)
 
-	if to <= from {
-		return fmt.Errorf("to height must be greater than from height: to: %d: from: %d: %w", to, from, gerrc.ErrInvalidArgument)
+	from, err := c.store.LoadBlockSyncBaseHeight()
```
Comment (omritoptix) [inline p2p/client.go:235]: same as my previous. from will be set to `0` which will cause very high iteration.

**Review by omritoptix — CHANGES_REQUESTED** [review]

File: block/manager.go (hunk 5 above)
Comment (srene) [reply block/manager.go]: removed

File: indexers/txindex/indexer_service.go (hunk 8 above)
Comment (srene) [reply indexers/txindex/indexer_service.go:107]: not sure what is the issue here, if not found it means it was never set and therefore it needs to start from 0 because it was never pruned...

File: store/pruning.go (hunk 6 above)
Comment (srene) [reply store/pruning.go]: i actually refactored the func to prune all indexes for every height iteration, so in case it fails it will be more likely all failed at the same height, although the solution not perfect. i created issue for this https://github.com/dymensionxyz/dymint/issues/1196

**Review by omritoptix — APPROVED** [review]
