### PR TITLE
fix(store): improve pruning to avoid skipped heights

### LINKED ISSUE #1039: Possible incosistencies when pruning
Quoting @srene 

>  there is a bug in the pruning which not sure it may cause some blocks are not pruned or it just cause inefficiency (ie some heights will skip pruning but it will prune later on). 2 i saw some inconsistencies about the retainheight returned but im not 100% sure abot that, maybe it was just a config issue, i have to recheck

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

## Opening a pull request should be able to meet the following requirements

In case there is some height with a key missing in the store, or in case pruning fails at a specific height for some reason, the pruning returns error.
In this PR this logic is changed and the pruning continues for other heights.
--

PR naming convention: https://hackmd.io/@nZpxHZ0CT7O5ngTp0TP9mg/HJP_jrm7A

---

Close #1039 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/pruning.go [hunk 1]
```diff
@@ -3,35 +3,35 @@ package block
...
 	if m.IsProposer() && m.NextHeightToSubmit() < retainHeight { // do not delete anything that we might submit in future
-		return fmt.Errorf("cannot prune blocks before they have been submitted: retain height %d: next height to submit: %d: %w",
-			retainHeight,
-			m.NextHeightToSubmit(),
-			gerrc.ErrInvalidArgument)
+		m.logger.Debug("cannot prune blocks before they have been submitted. using height last submitted height for pruning", "retain_height", retainHeight, "height_to_submit", m.NextHeightToSubmit())
+		retainHeight = m.NextHeightToSubmit() - 1
+		if retainHeight <= m.State.BaseHeight {
+			return 0, nil
+		}
```
Comment (danwt) [inline block/pruning.go:14]: Why is this `if` necessary?

File: block/pruning.go [hunk 2]
```diff
@@ -3,35 +3,35 @@ package block
...
 
-func (m *Manager) PruneBlocks(retainHeight uint64) error {
+func (m *Manager) PruneBlocks(retainHeight uint64) (uint64, error) {
 	if m.IsProposer() && m.NextHeightToSubmit() < retainHeight { // do not delete anything that we might submit in future
-		return fmt.Errorf("cannot prune blocks before they have been submitted: retain height %d: next height to submit: %d: %w",
-			retainHeight,
-			m.NextHeightToSubmit(),
-			gerrc.ErrInvalidArgument)
+		m.logger.Debug("cannot prune blocks before they have been submitted. using height last submitted height for pruning", "retain_height", retainHeight, "height_to_submit", m.NextHeightToSubmit())
+		retainHeight = m.NextHeightToSubmit() - 1
```
Comment (danwt) [inline block/pruning.go:11]: I think there is a race here because you read m.NextHeightToSubmit() twice it can change in between

File: block/pruning.go [hunk 3]
```diff
@@ -3,35 +3,35 @@ package block
 import (
 	"context"
 	"fmt"
-
-	"github.com/dymensionxyz/gerr-cosmos/gerrc"
 )
 
-func (m *Manager) PruneBlocks(retainHeight uint64) error {
+func (m *Manager) PruneBlocks(retainHeight uint64) (uint64, error) {
```
Comment (danwt) [inline block/pruning.go:8]: can you document return value

File: block/pruning_test.go [hunk 4]
```diff
@@ -63,10 +63,16 @@ func TestPruningRetainHeight(t *testing.T) {
 
 	validRetainHeight := lastSubmitted + 1 // the max possible valid retain height
 	for i := validRetainHeight + 1; i < manager.State.Height(); i++ {
-		err = manager.PruneBlocks(i)
-		require.Error(err) // cannot prune blocks before they have been submitted
+		expectedPruned := uint64(0)
+		if lastSubmitted >= manager.State.BaseHeight {
+			expectedPruned = lastSubmitted - manager.State.BaseHeight
+		}
```
Comment (danwt) [inline block/pruning_test.go:69]: can be 1 liner with math.max

File: p2p/client.go [hunk 5]
```diff
@@ -230,14 +230,14 @@ func (c *Client) RemoveBlocks(ctx context.Context, from, to uint64) error {
 	}
 
 	for h := from; h < to; h++ {
-
 		cid, err := c.store.LoadBlockCid(h)
 		if err != nil {
-			return fmt.Errorf("load block id from store %d: %w", h, err)
+			c.logger.Error("load blocksync block id from store", "height", h, "error", err)
+			continue
```
Comment (danwt) [inline p2p/client.go:236]: >  there is no cid stored for a specific height, which may happen

why may it happen?

Comment (danwt) [reply p2p/client.go:236]: I guess it can happen a lot right, since blocks maybe came from another source 👍

Comment (danwt) [reply p2p/client.go:236]: do you even need to log error then? probably want to differentiate not found vs parse error

File: block/pruning.go (hunk 2 above)
Comment (danwt) [reply block/pruning.go:11]: also isnt this off by one? why isn't retain height just m.NextHeightToSubmit(?

File: store/pruning.go [hunk 6]
```diff
@@ -16,7 +17,93 @@ func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
...
+
+	prunedSequencers, err := s.pruneSequencers(from, to)
+	if err != nil {
+		logger.Error("pruning sequencers", "from", from, "to", to, "sequencers pruned", prunedSequencers, "err", err)
+	}
+
+	prunedCids, err := s.pruneCids(from, to)
+	if err != nil {
+		logger.Error("pruning block sync identifiers", "from", from, "to", to, "cids pruned", prunedCids, "err", err)
+	}
```
Comment (danwt) [inline store/pruning.go:38]: logger.With() would be dryer

File: store/pruning.go [hunk 7]
```diff
@@ -3,11 +3,12 @@ package store
 import (
 	"fmt"
 
+	"github.com/dymensionxyz/dymint/types"
 	"github.com/dymensionxyz/gerr-cosmos/gerrc"
 )
 
 // PruneBlocks removes block up to (but not including) a height. It returns number of blocks pruned.
-func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
+func (s *DefaultStore) PruneStore(from, to uint64, logger types.Logger) (uint64, error) {
```
Comment (danwt) [inline store/pruning.go:11]: wrong docstring

File: store/pruning.go [hunk 8]
```diff
@@ -16,7 +17,93 @@ func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
...
+	return prunedSequencers, err
+}
+
+// pruneCids prunes content identifiers from store
+func (s *DefaultStore) pruneCids(from, to uint64) (uint64, error) {
+	pruneCids := func(batch KVBatch, height uint64) error {
+		if err := batch.Delete(getCidKey(height)); err != nil {
+			return err
+		}
+		return nil
```
Comment (danwt) [inline store/pruning.go:97]: can be 1 linea

File: store/pruning.go [hunk 9]
```diff
@@ -16,7 +17,93 @@ func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
...
+	return prunedResponses, err
+}
+
+// pruneSequencers prunes sequencers from store
+func (s *DefaultStore) pruneSequencers(from, to uint64) (uint64, error) {
+	pruneSequencers := func(batch KVBatch, height uint64) error {
+		if err := batch.Delete(getSequencersKey(height)); err != nil {
+			return err
+		}
+		return nil
```
Comment (danwt) [inline store/pruning.go:85]: can be 1 line

File: store/pruning.go [hunk 10]
```diff
@@ -16,7 +17,93 @@ func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
...
+	return prunedBlocks, err
+}
+
+// pruneResponses prunes block execution responses from store
+func (s *DefaultStore) pruneResponses(from, to uint64) (uint64, error) {
+	pruneResponses := func(batch KVBatch, height uint64) error {
+		if err := batch.Delete(getResponsesKey(height)); err != nil {
+			return err
+		}
+		return nil
```
Comment (danwt) [inline store/pruning.go:72]: can be 1 line

File: store/pruning.go [hunk 11]
```diff
@@ -29,29 +116,10 @@ func (s *DefaultStore) PruneBlocks(from, to uint64) (uint64, error) {
 	}
 
 	for h := from; h < to; h++ {
-		hash, err := s.loadHashFromIndex(h)
+		err := prune(batch, h)
 		if err != nil {
 			continue
 		}
```
Comment (danwt) [inline store/pruning.go:122]: dont you want to log these?

**Review by danwt — CHANGES_REQUESTED** [review]

File: block/pruning.go (hunk 2 above)
Comment (srene) [reply block/pruning.go]: fixed

File: block/pruning.go (hunk 3 above)
Comment (srene) [reply block/pruning.go:9]: done

File: p2p/client.go (hunk 5 above)
Comment (srene) [reply p2p/client.go:240]: done

File: block/pruning_test.go (hunk 4 above)
Comment (srene) [reply block/pruning_test.go]: fixed

File: store/pruning.go (hunk 11 above)
Comment (srene) [reply store/pruning.go]: log added

File: store/pruning.go (hunk 10 above)
Comment (srene) [reply store/pruning.go]: done

File: store/pruning.go (hunk 9 above)
Comment (srene) [reply store/pruning.go]: done

File: store/pruning.go (hunk 8 above)
Comment (srene) [reply store/pruning.go]: done

File: block/pruning.go (hunk 1 above)
Comment (srene) [reply block/pruning.go]: removed

**Review by danwt — DISMISSED** [review]

**Review by mtsitrin — APPROVED** [review]

File: store/store.go [hunk 12]
```diff
@@ -288,7 +289,7 @@ func (s *DefaultStore) SaveBlockCid(height uint64, cid cid.Cid, batch KVBatch) (
 func (s *DefaultStore) LoadBlockCid(height uint64) (cid.Cid, error) {
 	cidBytes, err := s.db.Get(getCidKey(height))
 	if err != nil {
-		return cid.Undef, fmt.Errorf("load cid for height %v: %w", height, err)
+		return cid.Undef, fmt.Errorf("load cid for height %v: %w", height, gerrc.ErrNotFound)
```
[the remark this answers is not in the document]
Comment (srene) [reply store/store.go]: yes, not sure why i changed it. fixed.

**Review by mtsitrin — APPROVED** [review]
