### PR TITLE
fix(da): full-nodes can sync from p2p while DA light client is down or out of sync

### LINKED ISSUE #856: fix(da): full-nodes should not wait for da to start syncing
if da light client is down, or out of sync, a full-node will not start, even though it could start syncing and caching packets from p2p

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

The main objective of this PR is the startup process for Celestia DA for full-nodes. With the modifications, full nodes will not wait for a DA to be in sync (or up) and it will do the syncing process in the background, while the full-node can start receiving and caching gossiped blocks from P2P. It also solves  a nil pointer error that was happening when DA light finished syncing and a full-node was started when was not still in sync. Without the modifications of this PR, a node could start receiving gossiped blocks, but everything received while DA was syncing was disregarded because the block manager was not started, waiting for the celestia light node to finish the syncing process.

## Opening a pull request should be able to meet the following requirements

---

Close #856 , #799 , https://github.com/dymensionxyz/dymint/issues/770

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: da/celestia/celestia.go [hunk 1]
```diff
@@ -138,39 +139,55 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
-		c.logger.Info("waiting for celestia-node to finish syncing", "height", state.Height, "target", state.ToHeight)
-
-		done := make(chan error, 1)
-		go func() {
-			done <- rpc.Header.SyncWait(c.ctx)
-		}()
-
-		ticker := time.NewTicker(1 * time.Minute)
-		defer ticker.Stop()
+	go retry.Do(
```
Comment (mtsitrin) [inline da/celestia/celestia.go:142]: I think simple for loop, with `state.Finished()` as break condition is more clearer.
IMO we shouldn't retry on errors for those queries, as it's an init process and errors should be popped up

**Review by mtsitrin — CHANGES_REQUESTED** [review]

File: block/manager.go [hunk 2]
```diff
@@ -218,15 +218,21 @@ func (m *Manager) onNewGossipedBlock(event pubsub.Message) {
...
 	block := eventData.Block
 	commit := eventData.Commit
-	m.logger.Debug("Received new block via gossip", "height", block.Header.Height, "n cachedBlocks", len(m.blockCache))
+
+	_, found := m.blockCache[block.Header.Height]
+	if found || block.Header.Height < m.Store.NextHeight() {
+		m.retrieverMutex.Unlock()
+		return
+	}
+	m.logger.Info("Received new block via gossip", "height", block.Header.Height, "n cachedBlocks", len(m.blockCache))
```
[the remark this answers is not in the document]
Comment (srene) [reply block/manager.go]: changed

File: block/manager.go [hunk 3]
```diff
@@ -218,15 +218,21 @@ func (m *Manager) onNewGossipedBlock(event pubsub.Message) {
...
 
 	nextHeight := m.Store.NextHeight()
 	if block.Header.Height >= nextHeight {
 		m.blockCache[block.Header.Height] = CachedBlock{
 			Block:  &block,
 			Commit: &commit,
 		}
-		m.logger.Debug("caching block", "block height", block.Header.Height, "store height", m.Store.Height())
+		m.logger.Info("caching block", "block height", block.Header.Height, "store height", m.Store.Height())
```
[the remark this answers is not in the document]
Comment (srene) [reply block/manager.go]: changed

File: da/celestia/celestia.go (hunk 1 above)
Comment (srene) [reply da/celestia/celestia.go:142]: a simple for loop will not start a celestia syncing process in background. the idea of this pr is that only sequencers must wait for syncing and full nodes can start receiving blocks without waiting for it. i think in this case, retry is necessary in case of any error or disconnection with da light happens, to continue with the process, without having to panic.

**Comment by danwt** [comment]
conflicts @srene

**Comment by danwt** [comment]
btw, solves https://github.com/dymensionxyz/dymint/issues/770?

**Comment by srene** [comment]
> btw, solves #770?

yes, the problem was coming from da stuck in the starting process when celestia was syncing meanwhile the node was starting to get batches. I opened a new issue for that, so i think we can close 770

File: da/celestia/celestia.go [hunk 4]
```diff
@@ -138,43 +139,60 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
+					ticker := time.NewTicker(1 * time.Minute)
+					defer ticker.Stop()
+
+					for {
+						select {
+						case err := <-done:
+							if err != nil {
+								return err
+							}
+							return nil
```
Comment (danwt) [inline da/celestia/celestia.go:168]: return err

File: da/celestia/celestia.go [hunk 5]
```diff
@@ -138,43 +139,60 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
 					return err
 				}
-				c.logger.Info("celestia-node still syncing", "height", state.Height, "target", state.ToHeight)
-			}
-		}
-	}
 
-	c.logger.Info("celestia-node is synced", "height", state.ToHeight)
+				if !state.Finished() {
+					c.logger.Info("waiting for celestia-node to finish syncing", "height", state.Height, "target", state.ToHeight)
```
Comment (danwt) [inline da/celestia/celestia.go:152]: seems like a redundant log given the log on 174

File: da/celestia/celestia.go [hunk 6]
```diff
@@ -138,43 +139,60 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
+							return nil
+						case <-ticker.C:
+							state, err := rpc.Header.SyncState(c.ctx)
+							if err != nil {
+								return err
+							}
+							c.logger.Info("celestia-node still syncing", "height", state.Height, "target", state.ToHeight)
+						}
+					}
+				}
```
Comment (danwt) [inline da/celestia/celestia.go:177]: seems this code could be simpler, and only have one line which calls SyncState
which would remove a redundant path

Comment (danwt) [reply da/celestia/celestia.go:177]:
```
// Start prepares DataAvailabilityLayerClient to work.
func (c *DataAvailabilityLayerClient) Start() (err error) {
	c.logger.Info("starting Celestia Data Availability Layer Client")

	// other client has already been set
	if c.rpc != nil {
		c.logger.Debug("celestia-node client already set")
		return nil
	}

	var rpc *openrpc.Client
	rpc, err = openrpc.NewClient(c.ctx, c.config.BaseURL, c.config.AuthToken)
	if err != nil {
		return err
	}

	go func() {
		sync := func() error {
			done := make(chan error, 1)
			go func() {
				done <- rpc.Header.SyncWait(c.ctx)
			}()
			ticker := time.NewTicker(1 * time.Minute)
			defer ticker.Stop()
			for {
				select {
				case err := <-done:
					return err
				case <-ticker.C:
					state, err := rpc.Header.SyncState(c.ctx)
					if err != nil {
						return err
					}
					if !state.Finished() {
						c.logger.Info("celestia-node still syncing", "height", state.Height, "target", state.ToHeight)
						continue
					}
					goto syncIsFinished
				}
			}

		syncIsFinished:
			c.rpc = NewOpenRPC(rpc)
			c.started <- struct{}{}
			c.logger.Info("celestia-node is synced", "height", state.ToHeight)

			return nil
		}

		err := retry.Do(sync,
			retry.Attempts(0), // try forever
			retry.Delay(10*time.Second),
			retry.LastErrorOnly(true),
			retry.DelayType(retry.FixedDelay),
		)
		if err != nil {
			c.logger.Error("Waiting for Celestia data availability client to sync", "err", err)
		}
	}()
	return 
}
```

does it work?

**Review by danwt — CHANGES_REQUESTED** [review]

File: da/celestia/celestia.go [hunk 7]
```diff
@@ -138,43 +139,60 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
-			select {
-			case err := <-done:
-				if err != nil {
-					return err
-				}
-				return nil
-			case <-ticker.C:
+	go func() {
+		err := retry.Do(
+			func() error {
```
[the remark this answers is not in the document]
Comment (srene) [reply da/celestia/celestia.go:144]: the start is called here: https://github.com/dymensionxyz/dymint/blob/73aae62f30acdc56816ad65550438d8830ac83db/node/node.go#L259

and i think the rpc can be not nil if already set as an option. i guess only used for testing to use with a mock rpc

File: da/celestia/celestia.go [hunk 8]
```diff
@@ -138,43 +139,60 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
 				state, err := rpc.Header.SyncState(c.ctx)
 				if err != nil {
+					c.logger.Error("Failed to start Celestia DA.", "Error", err)
 					return err
```
[the remark this answers is not in the document]
Comment (srene) [reply da/celestia/celestia.go]: if not logged, the retry func will swallow the error

File: da/celestia/celestia.go (hunk 6 above)
Comment (srene) [reply da/celestia/celestia.go]: i refactored the function using yours as a base

File: block/manager.go [hunk 9]
```diff
@@ -144,24 +143,27 @@ func (m *Manager) Start(ctx context.Context) error {
 		}
 	}
 
+	// Fullnode loop can start before syncing from DA
 	if !isSequencer {
 		go uevent.MustSubscribe(ctx, m.Pubsub, "applyGossipedBlocksLoop", p2p.EventQueryNewNewGossipedBlock, m.onNewGossipedBlock, m.logger)
+		go m.RetrieveLoop(ctx)
```
Comment (mtsitrin) [inline block/manager.go:149]: I think there's issue here.
now `syncUntilTarget` can be called in parallel, which makes no sense.
once from `syncBlockManager` and 2nd from `RetrieveLoop`

Comment (srene) [reply block/manager.go]: true. the retrieve loop should start only when the synblockmanager has finished, otherwise there can be two syncing processes in parallel. i fixed this.

Comment (srene) [reply block/manager.go]: i also moved that sequencers just wait for the da to be synced only to start producing blocks, since blobs can be retrieved even if da is not fully synced. i also renamed the channel to be more clear.

File: block/manager.go [hunk 10]
```diff
@@ -145,23 +144,28 @@ func (m *Manager) Start(ctx context.Context) error {
 	}
 
 	if !isSequencer {
+		// Fullnode loop can start before syncing from DA
 		go uevent.MustSubscribe(ctx, m.Pubsub, "applyGossipedBlocksLoop", p2p.EventQueryNewNewGossipedBlock, m.onNewGossipedBlock, m.logger)
 	}
 
+	// TODO: populate the accumulatedSize on startup
+
+	// Start syncing from DA
```
Comment (danwt) [inline block/manager.go:153]: useless comment, if `syncBlockManager` is hard to understand than rename the func instead

Comment (danwt) [inline block/manager.go:153]:
```suggestion
```

File: block/retriever.go [hunk 11]
```diff
@@ -38,6 +38,7 @@ func (m *Manager) RetrieveLoop(ctx context.Context) {
 // the actual blocks from the DA.
 func (m *Manager) syncUntilTarget(targetHeight uint64) error {
 	for currH := m.State.Height(); currH < targetHeight; currH = m.State.Height() {
+		m.logger.Info("Syncing from DA", "store height", currH, "target height", targetHeight)
```
Comment (danwt) [inline block/retriever.go:41]: please put info logs only **after** the thing that happened

so change to debug or moved to end of for loop and put `Synced`

File: da/celestia/celestia.go [hunk 12]
```diff
@@ -133,48 +134,54 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
+				select {
+				case err := <-done:
+					if err != nil {
+						c.logger.Error("Failed to start Celestia DA.", "Error", err)
+					}
 					return err
+				case <-ticker.C:
+					state, err := rpc.Header.SyncState(c.ctx)
+					if err != nil {
+						return err
```
Comment (danwt) [inline da/celestia/celestia.go:161]: want to log this one too?

**Review by danwt — CHANGES_REQUESTED** [review]
looks good just some nits

File: block/manager.go (hunk 10 above)
Comment (danwt) [reply block/manager.go:153]: I mean just `// Start syncing from DA`

File: da/celestia/celestia.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (danwt) [reply da/celestia/celestia.go]: ok good point

File: da/celestia/celestia.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (danwt) [reply da/celestia/celestia.go]: ok fine thanks

File: block/manager.go (hunk 10 above)
Comment (srene) [reply block/manager.go]: removed

File: block/retriever.go (hunk 11 above)
Comment (srene) [reply block/retriever.go]: done

File: block/manager.go [hunk 13]
```diff
@@ -252,3 +250,14 @@ func getInitialState(store store.Store, genesis *tmtypes.GenesisDoc, logger type
...
+func (m *Manager) startNonSequencerLoop(ctx context.Context) {
+	go uevent.MustSubscribe(ctx, m.Pubsub, "applyGossipedBlocksLoop", p2p.EventQueryNewNewGossipedBlock, m.onNewGossipedBlock, m.logger)
+	go m.RetrieveLoop(ctx)
+	go m.SyncTargetLoop(ctx)
+}
+
+func (m *Manager) startSequencerLoop(ctx context.Context) {
+	go m.ProduceBlockLoop(ctx)
+	go m.SubmitLoop(ctx)
+}
```
[the remark this answers is not in the document]
Comment (srene) [reply block/manager.go]: done

**Review by mtsitrin — APPROVED** [review]

File: da/celestia/celestia.go [hunk 14]
```diff
@@ -133,48 +134,55 @@ func (c *DataAvailabilityLayerClient) Start() (err error) {
...
+				case <-ticker.C:
+					state, err := rpc.Header.SyncState(c.ctx)
+					if err != nil {
+						c.logger.Error("Failed to sync Celestia DA.", "Error", err)
+						return err
+					}
+					if !state.Finished() {
+						c.logger.Info("celestia-node still syncing", "height", state.Height, "target", state.ToHeight)
+					}
 				}
```
Comment (mtsitrin) [inline da/celestia/celestia.go:167]: missing return here? in case `state.Finished()` is true

**Review by mtsitrin — CHANGES_REQUESTED** [review]

File: da/celestia/celestia.go (hunk 14 above)
Comment (srene) [reply da/celestia/celestia.go:167]: i think its fine not to return here, since in case there is no error the ticker is just used for logging the syncing progress. in case it finishes it will write to done channel by rpc.Header.SyncWait func and it will exit, or retry in case of error.
however, i realized there is a bug, finalizing before executing the retry function. i fixed it.

Comment (mtsitrin) [reply da/celestia/celestia.go:167]: so why checking `state.Finished()` at all? by your logic we could just log "sync in progress" on timer tick.
I guess we wanted a double check on the `SyncWait` signal

File: block/manager.go [hunk 15]
```diff
@@ -150,23 +149,27 @@ func (m *Manager) Start(ctx context.Context) error {
...
 	}
 
+	// TODO: populate the accumulatedSize on startup
+
 	err = m.syncBlockManager()
 	if err != nil {
 		return fmt.Errorf("sync block manager: %w", err)
 	}
 
+	// Sequencer producer loop and full-node retrieve loop is started only when finished syncing from DA
```
Comment (omritoptix) [inline block/manager.go:163]: the comment here seems incorrect in regards to the full node

File: da/celestia/celestia.go [hunk 16]
```diff
@@ -629,3 +604,46 @@ func (c *DataAvailabilityLayerClient) getDataAvailabilityHeaders(height uint64)
 
 	return headers.DAH, nil
 }
+
+// Celestia syncing in background
+func (c *DataAvailabilityLayerClient) syncCelestia(rpc *openrpc.Client) {
```
Comment (omritoptix) [inline da/celestia/celestia.go:609]: we're already in celestia so maybe just name the func `sync`?

File: da/celestia/celestia.go [hunk 17]
```diff
@@ -629,3 +604,46 @@ func (c *DataAvailabilityLayerClient) getDataAvailabilityHeaders(height uint64)
...
+		retry.Attempts(0), // try forever
+		retry.Delay(10*time.Second),
+		retry.LastErrorOnly(true),
+		retry.DelayType(retry.FixedDelay),
+	)
+
+	c.logger.Info("Celestia-node is synced.")
+	c.synced <- struct{}{}
+
+	if err != nil {
```
Comment (omritoptix) [inline da/celestia/celestia.go:646]: seems to me like this line will never be reached as we're trying forever.

File: da/celestia/celestia.go [hunk 18]
```diff
@@ -629,3 +604,46 @@ func (c *DataAvailabilityLayerClient) getDataAvailabilityHeaders(height uint64)
...
+					c.logger.Error("Failed to sync Celestia DA.", "Error", err)
+					return err
+				}
+				c.logger.Info("Celestia-node syncing", "height", state.Height, "target", state.ToHeight)
+
+			}
+		}
+	}
+
+	err := retry.Do(sync,
```
Comment (omritoptix) [inline da/celestia/celestia.go:636]: Instead of logging the error in the function I think we can just return a wrapped error and change the retry.Do to something like the following:

```
err := retry.Do(sync,
		retry.Attempts(0), // try forever
		retry.Delay(10*time.Second),
		retry.LastErrorOnly(true),
		retry.DelayType(retry.FixedDelay),
		retry.OnRetry(func(n uint, err error) {
			c.logger.Error("Retry sync due to error", "attempt", n, "error", err)
		}),
	)
```

Comment (srene) [reply da/celestia/celestia.go:632]: done

File: da/celestia/celestia.go (hunk 16 above)
Comment (srene) [reply da/celestia/celestia.go]: changed

File: block/manager.go (hunk 15 above)
Comment (srene) [reply block/manager.go]: that was supposed to be removed. fixed

File: da/celestia/celestia.go (hunk 17 above)
Comment (srene) [reply da/celestia/celestia.go:645]: but i guess we need to catch the error of the retry function and do something with it in case it fails, anyway..

Comment (omritoptix) [reply da/celestia/celestia.go:645]: ok we can leave it.

**Review by omritoptix — APPROVED** [review]
