### PR TITLE
fix: changing dymint rpc to enable queries for unhealthy nodes

### LINKED ISSUE #576: upon unhealthy keep queries alive
currently the entire node queries return the error. 
Only the tx endpoints should be disabled and the queries should still function. 
we should have an health endpoint just for that.

### PR DESCRIPTION
**Pull request by srene**
# Description

- currently the entire node queries return error when nodes are set to unhealthy state, after receiving an unhealthy event. 
- with the modifications, we enable a new rpc endpoint"/health", to be able to query the health status of the node, but other rpc are still available. 
- all responses attach the health status of the node

Closes #576 
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: rpc/middleware/client.go [hunk 1]
```diff
@@ -24,7 +25,7 @@ func NewClient(reg Registry, logger log.Logger) *Client {
 // Handle wraps the provided http.Handler with the registered middlewares and returns the final http.Handler.
 func (mc *Client) Handle(h http.Handler) http.Handler {
 	registeredMiddlewares := mc.registry.GetRegistered()
-
+	fmt.Println("handle")
```
Comment (mtsitrin) [inline rpc/middleware/client.go:28]: remove

File: rpc/middleware/status.go [hunk 2]
```diff
@@ -24,29 +25,58 @@ func NewStatusMiddleware(healthStatus *sharedtypes.HealthStatus) *StatusMiddlewa
...
 func (s *StatusMiddleware) Handler(logger log.Logger) HandlerFunc {
 	return func(h http.Handler) http.Handler {
-		return status(s.healthStatus, h, logger)
-	}
-}
+		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+
+			isHealthy, err := s.healthStatus.Get()
+			//in case the endpoint is health we return health response
+			if r.URL.Path == "/health" {
```
Comment (mtsitrin) [inline rpc/middleware/status.go:32]: IMO it should be added on the handler, no need for middlware to handle this URI

**Comment by mtsitrin** [comment]
@srene why we need to `all responses attach the health status of the node`?

File: rpc/middleware/client.go (hunk 1 above)
Comment (srene) [reply rpc/middleware/client.go]: done
