### PR TITLE
fix(rpc): nil panic in rpc/json/handler.go WriteError

### LINKED ISSUE #751: Found a nil pointer panic in rpc/json/handler.go
Caused by passing `nil` to `WriteError`

### PR DESCRIPTION
**Pull request by zale144**
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Close #751 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: rpc/json/handler.go [hunk 1]
```diff
@@ -70,6 +71,7 @@ func (h *handler) serveJSONRPCforWS(w http.ResponseWriter, r *http.Request, wsCo
 	}
 	methodSpec, ok := h.srv.methods[method]
 	if !ok {
+		err := fmt.Errorf("method %s not found", method)
```
Comment (danwt) [inline rpc/json/handler.go:74]:
```suggestion
		err := fmt.Errorf("method not found: %s", method)
```

**Review by danwt — CHANGES_REQUESTED** [review]

**Review by danwt — APPROVED** [review]
nice!

**Review by VictorTrustyDev — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]
