### PR TITLE
fix(p2p): handle default mempool check tx error case

### LINKED ISSUE #661: Validating gossiped transactions may block the libp2p validator queue

### PR DESCRIPTION
**Pull request by zale144**
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

Close #661 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: p2p/validator_test.go [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+				numMsgs: 3,
+			},
+			want: true,
+		}, {
+			name: "valid: mempool is full",
+			args: args{
+				mp:      &mockMP{err: mempool.ErrMempoolIsFull{}},
+				numMsgs: 3,
+			},
+			want: true,
```
Comment (danwt) [inline p2p/validator_test.go:41]: I know you didn't write it but why is it valid if the MP is full?

```
// TxValidator creates a pubsub validator that uses the node's mempool to check the
// transaction. If the transaction is valid, then it is added to the mempool.
func (v *Validator) TxValidator
```


>If the transaction is valid, then it is added to the mempool.

**Review by danwt — APPROVED** [review]
Nice simplification!
I'm a bit confused about the mempool is full case 😕

File: p2p/validator_test.go (hunk 1 above)
Comment (zale144) [reply p2p/validator_test.go:41]: I was wondering the same thing. @omritoptix ?

Comment (zale144) [reply p2p/validator_test.go:41]: @danwt btw, the audit claims that if there is an unhandled error type in the switch, the goroutine will block. They were wrong, it won't block, for every new tx a new buffered (1) channel is created.

Which makes me wonder, why was there a channel in the first place? we're just grabbing a value from a lower scope 🤷

Comment (danwt) [reply p2p/validator_test.go:41]: yeah, greaaaaaaat question haha

maybe it used to be necessary and it got refactored and they forgot to remove the channel
or it was never necessary and original author simply made a mistake 🤷

Comment (danwt) [reply p2p/validator_test.go:41]: let's anyway merge your nice fix and address the mempool full thing seperately

**Comment by mtsitrin** [comment]
looks good!

**Review by omritoptix — APPROVED** [review]

File: p2p/validator_test.go (hunk 1 above)
Comment (omritoptix) [reply p2p/validator_test.go:41]:
```
// CheckTx executes a new transaction against the application to determine
// its validity and whether it should be added to the mempool.
```

```
// If the application accepts the transaction and the mempool is full, the
// mempool evicts one or more of the lowest-priority transaction whose priority
// is (strictly) lower than the priority of tx and whose size together exceeds
// the size of tx, and adds tx instead. If no such transactions exist, tx is
// discarded.
```

In that sense check tx verifies validity and not the fact that it can be added to the pool (but rather should). even if it can't be added to the pool it doesn't mean it's invalid.
