### PR TITLE
fix(p2p): validate block before applying and not before caching in p2p gossiping

### LINKED ISSUE #722: p2p gossiped blocks fails in validation
the following error is triggered when using p2p gossip:
ERRO[0083] apply block callback, block not valid: dropping it[err block: b height mismatch height 96]  module=BlockManager

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

P2P gossiping tries to validate blocks on reception. However, the validation fails if blocks are received unordered, dropping them, and being unable to sync using p2p for any block received after. This PR fixes the issue validating blocks in order, moving the validation call after caching them, and before applying, once all blocks are received and can be applied in order.

## Opening a pull request should be able to meet the following requirements

---

Close #722 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/block.go [hunk 1]
```diff
@@ -130,8 +130,12 @@ func (m *Manager) attemptApplyCachedBlocks() error {
 		if !blockExists {
 			break
 		}
+		if err := m.validateBlock(cachedBlock.Block, cachedBlock.Commit); err != nil {
```
Comment (omritoptix) [inline block/block.go:133]: thinking we should delete it and not keep it in cache.

Comment (srene) [reply block/block.go:133]: block deleted from cache if invalid.

**Review by omritoptix — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]

**Review by danwt — COMMENTED** [review]
this reintroduces a problem found in the audit which is that bad blocks can overwrite good ones in the cache

File: block/block.go [hunk 2]
```diff
@@ -130,8 +130,12 @@ func (m *Manager) attemptApplyCachedBlocks() error {
...
+			delete(m.blockCache, cachedBlock.Block.Header.Height)
+			/// TODO: can we take an action here such as dropping the peer / reducing their reputation?
+			return fmt.Errorf("block not valid at height %d, dropping it: err:%w", cachedBlock.Block.Header.Height, err)
```
Comment (danwt) [inline block/block.go:136]: height should go at the end
don't need 'err'

**Comment by danwt** [comment]
https://github.com/dymensionxyz/dymint/issues/656
