### PR TITLE
fix(da): full-node get the da fetch configuration from hub and not config

### LINKED ISSUE #718: full-node should use namespace id obtained from batch, and not from config
Right now, full-node checks availability and retrieves batches using the namespace id from da_config param. However, it makes more sense to check availability and retrieve batch using namespace id written in the da path by the sequencer,  disregarding config parameter, since this can be a potential misconfiguration issue.

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

This is a code refactor to avoid using namespace id param from configuration in full-nodes, since it is not relevant and it can lead to potential config issues, and the important is the namespace used by sequencer when posting batches.

## Opening a pull request should be able to meet the following requirements

---

Close #718 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: da/celestia/celestia.go [hunk 1]
```diff
@@ -443,6 +431,7 @@ func (c *DataAvailabilityLayerClient) checkBatchAvailability(daMetaData *da.DASu
 	DACheckMetaData.Height = daMetaData.Height
 	DACheckMetaData.Client = daMetaData.Client
```
Comment (omritoptix) [inline da/celestia/celestia.go:432]: Possibly cleaner to initialize while defining the object:

```
DACheckMetaData := &da.DACheckMetaData{
		Client:     daMetaData.Client,
		Height:     daMetaData.Height,
		Commitment: daMetaData.Commitment,
		Namespace:  daMetaData.Namespace,
	}
```

**Review by omritoptix — APPROVED** [review]
