### PR TITLE
fix(p2p): avoid receiving duplicated blocks

### LINKED ISSUE #795: discard duplicated packets received via gossip
it seems nodes can receive duplicated blocks. we need to investigate why, and avoid calling onNewGossipedBlock for duplicated

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

This PR is aimed at preventing the reception of duplicated blocks from p2p network, by updating Gossipsub router configuration. It also prevents adding blocks to cache when already received. This improves performance and syncing times, because receiving too many packets from p2p may block applying blocks received from DA.

## Opening a pull request should be able to meet the following requirements

---

Close #795 #803 
<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: block/manager.go [hunk 1]
```diff
@@ -240,21 +240,26 @@ func (m *Manager) onNodeHealthStatus(event pubsub.Message) {
 // TODO: move to gossip.go
 // onNewGossippedBlock will take a block and apply it
 func (m *Manager) onNewGossipedBlock(event pubsub.Message) {
-	m.retrieverMutex.Lock() // needed to protect blockCache access
-	m.logger.Debug("Received new block via gossip", "n cachedBlocks", len(m.blockCache))
 	eventData := event.Data().(p2p.GossipedBlock)
 	block := eventData.Block
 	commit := eventData.Commit
 
+	_, found := m.blockCache[block.Header.Height]
```
Comment (mtsitrin) [inline block/manager.go:247]: this also needs mutex access
maybe move right above
`m.blockCache[block.Header.Height] =`

**Review by mtsitrin — CHANGES_REQUESTED** [review]

File: block/manager.go (hunk 1 above)
Comment (srene) [reply block/manager.go:249]: moved

File: block/manager.go [hunk 2]
```diff
@@ -237,21 +237,28 @@ func (m *Manager) onNodeHealthStatus(event pubsub.Message) {
...
 	commit := eventData.Commit
 	m.logger.Debug("Received new block via gossip", "height", block.Header.Height, "n cachedBlocks", len(m.blockCache))
+	m.retrieverMutex.Lock() // needed to protect blockCache access
+	_, found := m.blockCache[block.Header.Height]
+	if found {
+		m.retrieverMutex.Unlock()
+		return
+	}
+
+	m.logger.Debug("Received new block via gossip", "block height", block.Header.Height, "store height", m.Store.Height(), "n cachedBlocks", len(m.blockCache))
```
Comment (danwt) [inline block/manager.go:251]: almost duplicate line of above line 243

**Review by danwt — CHANGES_REQUESTED** [review]
not sure if I understood what is the point of this pr?
There was too much demand for the mutex before?

File: block/manager.go (hunk 2 above)
Comment (srene) [reply block/manager.go:250]: true, it's been re-added by mistake. removed

**Comment by srene** [comment]
> not sure if I understood what is the point of this pr? There was too much demand for the mutex before?

it avoids receiving extra duplicates from gossipsub protocol by passing extra options in p2p/client.go, this reduces the demand of the mutex. also it avoids adding already received blocks to the cache, in case it happens.

File: p2p/client.go [hunk 3]
```diff
@@ -320,9 +320,9 @@ func (c *Client) tryConnect(ctx context.Context, peer peer.AddrInfo) {
 func (c *Client) setupGossiping(ctx context.Context) error {
 	pubsub.GossipSubHistoryGossip = c.conf.GossipCacheSize
 	pubsub.GossipSubHistoryLength = c.conf.GossipCacheSize
-	pubsub.GossipSubMaxIHaveMessages = c.conf.GossipCacheSize
 
-	ps, err := pubsub.NewGossipSub(ctx, c.Host)
+	//We add WithSeenMessagesTTL (with 1 year time) option to avoid ever requesting already seen blocks
+	ps, err := pubsub.NewGossipSub(ctx, c.Host, pubsub.WithSeenMessagesTTL(8760*time.Hour))
```
Comment (mtsitrin) [inline p2p/client.go:325]: can u explain this 1 year time? previously u had 
`time.Duration(int(c.blockTime.Nanoseconds()*int64(c.conf.GossipCacheSize))))`

Comment (srene) [reply p2p/client.go]: i removed the ttl option and replaced gossipsub version with a new version where seen packets are not expiring

File: block/manager.go [hunk 4]
```diff
@@ -237,21 +237,27 @@ func (m *Manager) onNodeHealthStatus(event pubsub.Message) {
...
 	eventData := event.Data().(p2p.GossipedBlock)
 	block := eventData.Block
 	commit := eventData.Commit
-	m.logger.Debug("Received new block via gossip", "height", block.Header.Height, "n cachedBlocks", len(m.blockCache))
+	m.retrieverMutex.Lock() // needed to protect blockCache access
+	_, found := m.blockCache[block.Header.Height]
+	if found {
+		m.retrieverMutex.Unlock()
+		return
+	}
```
Comment (danwt) [inline block/manager.go:248]: can you add a comment here explaining why we return early?
Like your explanation here https://github.com/dymensionxyz/dymint/pull/818#issuecomment-2103415147
Because otherwise, to a new reader, it probably looks like a useless branch

**Review by danwt — CHANGES_REQUESTED** [review]

File: block/manager.go (hunk 4 above)
Comment (srene) [reply block/manager.go:248]: we return early if the block is already received, since it is not necessary to cache again the same block (and therefore avoid attempting applying blocks if actually no new block is received).

File: block/manager.go [hunk 5]
```diff
@@ -237,21 +237,28 @@ func (m *Manager) onNodeHealthStatus(event pubsub.Message) {
...
 // onNewGossippedBlock will take a block and apply it
 func (m *Manager) onNewGossipedBlock(event pubsub.Message) {
-	m.retrieverMutex.Lock() // needed to protect blockCache access
 	eventData := event.Data().(p2p.GossipedBlock)
 	block := eventData.Block
 	commit := eventData.Commit
-	m.logger.Debug("Received new block via gossip", "height", block.Header.Height, "n cachedBlocks", len(m.blockCache))
+	m.retrieverMutex.Lock() // needed to protect blockCache access
+	_, found := m.blockCache[block.Header.Height]
+	//we return early if the block is already received, since it is not necessary to cache again the same block (and therefore it is not necessary to call attemptApplyCachedBlocks() if actually no new block is received).
```
Comment (danwt) [inline block/manager.go:245]:
```suggestion
	// It is not strictly necessary to return early, for correctness, but doing so helps us avoid mutex pressure and unnecessary repeated attempts to apply cached blocks
```

**Review by danwt — APPROVED** [review]
nice!

**Review by omritoptix — APPROVED** [review]

**Comment by omritoptix** [comment]
@mtsitrin can we merge?
