### PR TITLE
fix(sl): fix fail on startup for rollapp without state update

### LINKED ISSUE #1404: error when starting rollapp node for rollapp without state updates
```
Error: while starting block manager: get proposer at height: get batch at height: get state info: query state info: rpc error: code = NotFound desc = LatestStateInfoIndex wasn't found for rollappId=rollappsui_901082-1: not found: key not found
Usage:
```

This error is caused by a bug introduced by this pr https://github.com/dymensionxyz/dymint/pull/1399. 
the problem comes from the ` errors.Join(gerrc.ErrNotFound` was removed, but it shouldnt

### PR DESCRIPTION
**Pull request by srene**
# PR Standards

This PR is aimed at fixing a bug that causes node cannot start for rollapps without state updates. 
It basically readds the errors.Join(gerrc.ErrNotFound, err) for getstateinfo(),  that was removed by mistake. 
it also adds the option to retry or not when getting state info depending on the case.

## Opening a pull request should be able to meet the following requirements

--

PR naming convention: https://hackmd.io/@nZpxHZ0CT7O5ngTp0TP9mg/HJP_jrm7A

---

Close #1404 

<-- Briefly describe the content of this pull request -->

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

**Review by omritoptix — COMMENTED** [review]
wouldn't it be simpler to just add the bool `tryRetry` as an optional argument to the  `getBatchAtHeight` vs creating a new method `getBatchAtHeightNoRetry`?

**Comment by srene** [comment]
> wouldn't it be simpler to just add the bool `tryRetry` as an optional argument to the `getBatchAtHeight` vs creating a new method `getBatchAtHeightNoRetry`?

done

File: block/fork.go [hunk 1]
```diff
@@ -220,7 +220,7 @@ func (m *Manager) createForkBlocks(instruction types.Instruction, consensusMsgs
 //  1. Checks for an existing batch at the specified height via SLClient
 //  2. If no batch exists, creates and submits a new one
 func (m *Manager) submitForkBatch(height uint64) error {
-	resp, err := m.SLClient.GetBatchAtHeight(height)
+	resp, err := m.SLClient.GetBatchAtHeight(height, true)
```
Comment (omritoptix) [inline block/fork.go:223]: unnecessary as by default it's true

Comment (srene) [reply block/fork.go]: i missed this one. fixed

**Review by omritoptix — APPROVED** [review]
